### ISSUE TITLE
Camera is not getting displayed but QR is scanned in case of "Scan in Preview"

### ISSUE THREAD

**Issue by iOSDevAkshay** [yannickl/QRCodeReader.swift#119] opened 2017-10-12 07:32 UTC
Xcode 8.3.2 , Swift 3

In example when Scan In Preview option is selected camera doesnt appear .

Please help me with the same , 
Thank you in advance

**Comment by yannickl** [comment] 2017-10-15 20:28
Hi, which version of `QRCodeReader.swift` are you using?

**Comment by yannickl** [comment] 2017-10-21 20:40
Duplicate of #120

**Closed by yannickl** 2017-10-21 20:40 UTC

**Comment by iOSDevAkshay** [comment] 2017-10-23 11:20
8.0.3 . latest one . In your example itself it camera  is not opening inside view .
