### ISSUE TITLE
iOS 10 deprecation warnings on `devices(withMediaType:)` in Xcode 8 GM

### ISSUE THREAD

**Issue by dpcrook** [yannickl/QRCodeReader.swift#56] opened 2016-09-07 21:27 UTC
I was trying compile a project in Xcode 8.0 GM (swift3 branch), and got new deprecation warnings.

Screen captures below

![screenshot 2016-09-07 15 26 36](https://cloud.githubusercontent.com/assets/461806/18329188/813509f6-750f-11e6-9ba6-d54bd5d8c535.png)

![screenshot 2016-09-07 15 22 59](https://cloud.githubusercontent.com/assets/461806/18329086/204c3506-750f-11e6-8a7a-679a349eecdb.png)

Don't have time to fix at the moment so thought I'd file an issue.

**Comment by yannickl** [comment] 2016-09-07 21:29
I just downloaded the Xcode8 GM, I'll update the library tomorrow. Thank you for the hint!

**Comment by yannickl** [comment] 2016-09-08 10:20
The problem is fixed now! 👍

**Closed by yannickl** 2016-09-08 10:20 UTC
